### ISSUE TITLE
Unable to run the application

### ISSUE THREAD

**Issue by Asifislam110** [abhishekkhandait/Angular2-Task-board#1]
I've downloaded your repository and ran npm install  but I was not able to run it locally.

Facing the issue

ERROR in /Angular2-Task-board-master/Angular2-Task-board-master/src/app/board/board.component.ts (7,10): Module '"/Angular2-Task-board-master/Angular2-Task-board-master/node_modules/@angular/material/material"' has no exported member 'MdDialog'.
ERROR in /Angular2-Task-board-master/Angular2-Task-board-master/src/app/board/board.component.ts (7,20): Module '"/Angular2-Task-board-master/Angular2-Task-board-master/node_modules/@angular/material/material"' has no exported member 'MdDialogRef'.
ERROR in /Angular2-Task-board-master/Angular2-Task-board-master/src/app/app.module.ts (5,10): Module '"/Angular2-Task-board-master/Angular2-Task-board-master/node_modules/@angular/material/material"' has no exported member 'MaterialModule'.
ERROR in Error: MaterialModule is not an NgModule
    at _getNgModuleMetadata (\Angular2-Task-board-master\Angular2-Task-board-master\node_modules\@angular\compiler-cli\src\ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (\Angular2-Task-board-master\Angular2-Task-board-master\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at \Angular2-Task-board-master\Angular2-Task-board-master\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (\Angular2-Task-board-master\Angular2-Task-board-master\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (\Angular2-Task-board-master\Angular2-Task-board-master\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (\Angular2-Task-board-master\Angular2-Task-board-master\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (\Desktop\Angular2-Task-board-master\Angular2-Task-board-master\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (\Desktop\Angular2-Task-board-master\Angular2-Task-board-master\node_modules\@ngtools\webpack\src\plugin.js:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in /Angular2-Task-board-master/Angular2-Task-board-master/src/app/app.module.ts (5,10): Module '"/Angular2-Task-board-master/Angular2-Task-board-master/node_modules/@angular/material/material"' has no exported member 'MaterialModule'.
ERROR in /Angular2-Task-board-master/Angular2-Task-board-master/src/app/board/board.component.ts (7,10): Module '"/Angular2-Task-board-master/Angular2-Task-board-master/node_modules/@angular/material/material"' has no exported member 'MdDialog'.
ERROR in /Angular2-Task-board-master/Angular2-Task-board-master/src/app/board/board.component.ts (7,20): Module '"/Angular2-Task-board-master/Angular2-Task-board-master/node_modules/@angular/material/material"' has no exported member 'MdDialogRef'.

**Comment by abhishekkhandait** [comment]
Since material 2.0.0-beta.11, we need change the Md to Mat for all the imported modules. [Migration Tool](https://www.npmjs.com/package/angular-material-prefix-updater) didnt work. Working on changing md to mat manually.
